# Generated by Django 4.1.2 on 2022-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=32)),
                ('user_password', models.CharField(default=None, max_length=32, null=True)),
                ('agora_chat_user_name', models.CharField(max_length=32)),
                ('agora_chat_user_uuid', models.CharField(default=None, max_length=36, null=True)),
            ],
        ),
    ]
