# Generated by Django 4.1.2 on 2022-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appuserinfo',
            constraint=models.UniqueConstraint(fields=('id', 'user_account'), name='id_user_account_unique_constraint'),
        ),
    ]
