platform :ios, '11.0'


# Import CocoaPods sources
#source 'https://github.com/CocoaPods/Specs.git'

target 'AgoraChatAPIExample' do

    pod 'Agora_Chat_iOS'
    pod 'Masonry'
    pod 'EMVoiceConvert', '0.1.0'
end

