#use_frameworks!
platform :ios, '11.0'


# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatKitExample' do

    pod 'Masonry'
    pod 'chat-uikit',  :path => "../AgoraChatKit"
  
end

