# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'AgoraChatAPIExample-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Agora_Chat_iOS','1.0.6'
  pod 'ZSwiftBaseLib','0.1.4'
  pod 'ProgressHUD'
end
